# permissions for end users to edit fulldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fulldeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kuberentes-operator
    app.kubernetes.io/part-of: kuberentes-operator
    app.kubernetes.io/managed-by: kustomize
  name: fulldeployment-editor-role
rules:
- apiGroups:
  - kmerkuri.kmerkuri.io
  resources:
  - fulldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kmerkuri.kmerkuri.io
  resources:
  - fulldeployments/status
  verbs:
  - get
